# Build Stage - 1
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# Production Runtime Stage
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

ENV PORT=4000


COPY --from=builder /app/package*.json ./
COPY --from=builder /app/apps/api/dist ./apps/api/dist/
COPY --from=builder /app/node_modules ./node_modules/

EXPOSE 4000

#WORKDIR /app/apps/api

CMD ["node", "apps/api/dist/server.js"]
